{% set version = "6.3.1" %}

package:
  name: beautysh
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/b/beautysh/beautysh-{{ version }}.tar.gz
    sha256: 58eb9d67627c09d0565e0e77892c5ff7cb7ba086cdac7e960452757daff14410
    folder: dist
  - url: https://github.com/lovesegfault/beautysh/archive/v{{ version }}.tar.gz
    sha256: 83d0941a323bf46c83f396a4a4d3aa5755af6ac9c673d61f7e516b540b56f707
    folder: src

build:
  noarch: python
  number: 0
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - beautysh = beautysh:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - colorama >=0.4.4,<0.5
    - python >={{ python_min }}
    - setuptools
    - types-colorama >=0.4.3,<0.5
    - types-setuptools >=57.4.0,<58

test:
  source_files:
    - src/tests
  requires:
    - coverage
    - pip
    - pytest <7
    - python {{ python_min }}
  imports:
    - beautysh
  commands:
    - pip check
    - beautysh --version
    - beautysh --help
    - cd src
    - coverage run --source beautysh --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=55

about:
  home: https://github.com/bemeurer/beautysh
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: A Bash beautifier for the masses.

extra:
  recipe-maintainers:
    - lovesegfault
    - bollwyvl
    - dbast
