{% set name = "beautysh" %}
{% set version = "6.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 966b4acb877ad3606a96524e42c8368f0fdff30058340b497788ec4161b7d544
    folder: dist
  - url: https://github.com/lovesegfault/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 136c40c8da7726d517638616cd585194c8c80a4ddc83874a6ce8158b72ac5124
    folder: src

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - beautysh = beautysh:main

requirements:
  host:
    - pip
    - python >=3
    - poetry-core >=1.0.0
  run:
    - python >=3
    - setuptools

test:
  source_files:
    - src/tests
  requires:
    - pip
    - pytest-cov
  imports:
    - beautysh
  commands:
    - beautysh --version
    - beautysh --help
    - python -m pip check
    # coverage 61% as of 6.0.1
    - cd src && pytest --cov beautysh --cov-fail-under 60

about:
  home: https://github.com/bemeurer/beautysh
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: A Bash beautifier for the masses.

extra:
  recipe-maintainers:
    - lovesegfault
    - bollwyvl
    - dbast
