{% set version = "6.4.0" %}

package:
  name: beautysh
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/b/beautysh/beautysh-{{ version }}.tar.gz
    sha256: d758d74e81ed11d073e0ebafe817b030f7745773a648748f68dbd5e9ecd1c8a0
    folder: dist
  - url: https://github.com/lovesegfault/beautysh/archive/v{{ version }}.tar.gz
    sha256: ca1ab92c9278dd5395e3a32168e2b3731e10bde4fc691f93620b9b19413bc073
    folder: src

build:
  noarch: python
  number: 0
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - colorama >=0.4.4
    - editorconfig >=0.12.0
    - tomli

test:
  source_files:
    - src/tests
  requires:
    - coverage
    - pip
    - pytest >=7.0.0
    - python {{ python_min }}
  imports:
    - beautysh
  commands:
    - pip check
    - beautysh --version
    - beautysh --help
    - cd src
    - coverage run --source beautysh --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=55

about:
  home: https://github.com/bemeurer/beautysh
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: A Bash beautifier for the masses.

extra:
  recipe-maintainers:
    - lovesegfault
    - bollwyvl
    - dbast
