{% set version = "6.2.1" %}

package:
  name: beautysh
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/b/beautysh/beautysh-{{ version }}.tar.gz
    sha256: 423e0c87cccf2af21cae9a75e04e0a42bc6ce28469c001ee8730242e10a45acd
    folder: dist
  - url: https://github.com/lovesegfault/beautysh/archive/v{{ version }}.tar.gz
    sha256: 0d158ad19e7f24018c62692ac36929d165ee2ba0f6dfa50c262db32f426eacd6
    folder: src

build:
  noarch: python
  number: 1
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - beautysh = beautysh:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - colorama >=0.4.4,<0.5
    - python >={{ python_min }}
    - setuptools
    - types-colorama >=0.4.3,<0.5
    - types-setuptools >=57.4.0,<58

test:
  source_files:
    - src/tests
  requires:
    - coverage
    - pip
    - pytest <7
    - python {{ python_min }}
  imports:
    - beautysh
  commands:
    - pip check
    - beautysh --version
    - beautysh --help
    - cd src
    - coverage run --source beautysh --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=55

about:
  home: https://github.com/bemeurer/beautysh
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: A Bash beautifier for the masses.

extra:
  recipe-maintainers:
    - lovesegfault
    - bollwyvl
    - dbast
