{% set name = "beautysh" %}
{% set version = "6.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 423e0c87cccf2af21cae9a75e04e0a42bc6ce28469c001ee8730242e10a45acd
    folder: dist
  - url: https://github.com/lovesegfault/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 0d158ad19e7f24018c62692ac36929d165ee2ba0f6dfa50c262db32f426eacd6
    folder: src

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - beautysh = beautysh:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6.2
  run:
    - colorama >=0.4.4,<1
    - python >=3.6.2
    - setuptools
    - types-colorama >=0.4.3,<1
    - types-setuptools >=57.4.0,<58

test:
  source_files:
    - src/tests
  requires:
    - pip
    - pytest-cov
  imports:
    - beautysh
  commands:
    - pip check
    - beautysh --version
    - beautysh --help
    # coverage 61% as of 6.0.1
    - cd src && pytest --cov beautysh --cov-fail-under 60

about:
  home: https://github.com/bemeurer/beautysh
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: A Bash beautifier for the masses.

extra:
  recipe-maintainers:
    - lovesegfault
    - bollwyvl
    - dbast
