# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 6.4.0
  python_check_max: "3.14"

package:
  name: beautysh
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/beautysh/beautysh-${{ version }}.tar.gz
  sha256: d758d74e81ed11d073e0ebafe817b030f7745773a648748f68dbd5e9ecd1c8a0

build:
  number: 0
  noarch: python
  python:
    entry_points:
      - beautysh = beautysh.__main__:main
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - colorama >=0.4.4
    - editorconfig >=0.12.0
    - tomli >=1.0.0

tests:
  - python:
      imports: beautysh
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - tests/
    requirements:
      run:
        - coverage
        - hypothesis >=6.0.0
        - pytest >=7.0.0
        - python ${{ python_min }}.*
        - pyyaml
    script:
      - beautysh --version
      - beautysh --help
      - coverage run --source beautysh --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=55

about:
  license: MIT
  license_file: LICENSE
  summary: A Bash beautifier for the masses.
  homepage: https://github.com/bemeurer/beautysh

extra:
  recipe-maintainers:
    - lovesegfault
    - bollwyvl
    - dbast
